let primeiroNome = prompt("Qual o seu primeiro nome?")
let sobrenome = prompt("Agora digite o seu sobrenome")
let campoEstudo = prompt("Qual o seu campo de estudo?")
let idade = (2024 - prompt("Em que ano você nasceu?"))
alert("Bem vindo recruta "+primeiroNome+"! Seu campo de estudo digitado foi "+campoEstudo+" e com base nos meus calculos você tem aproximadamente "+idade+" anos.")